name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm i --force

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: 4p9PuyT7vB1snuX2Eh01ZR6c_Zjc57uGpcIavscP
          accountId: 8a8fe81de85a52a0edd5cc5f115785b7
          projectName: daric-coin # Replace with your Cloudflare Pages project name
          directory: out
          # Optional: Enable SPA mode for client-side routing
          # singlePageApp: true
          # Optional: Add custom domain
          # customDomain: your-domain.com